### ISSUE TITLE
Warnings & Fatal errors?

### ISSUE THREAD

**Issue by jezthomp** [tlovett1/simple-cache#117]
Does my hosting have the right settings to run this, just turned on for the first time and have these errors?
```

`Warning: Use of undefined constant WP_PLUGIN_DIR - assumed 'WP_PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /home/whitehouse/public_html/wp-content/advanced-cache.php on line 5

Warning: include_once(WP_PLUGIN_DIR/simple-cache/inc/pre-wp-functions.php): failed to open stream: No such file or directory in /home/whitehouse/public_html/wp-content/advanced-cache.php on line 5

Warning: include_once(): Failed opening 'WP_PLUGIN_DIR/simple-cache/inc/pre-wp-functions.php' for inclusion (include_path='.:/usr/share/php') in /home/whitehouse/public_html/wp-content/advanced-cache.php on line 5

Fatal error: Uncaught Error: Call to undefined function sc_load_config() in /home/whitehouse/public_html/wp-content/advanced-cache.php:6 Stack trace: #0 /home/whitehouse/public_html/wp-settings.php(97): include() #1 /home/whitehouse/public_html/wp-config.php(99): require_once('/home/whitehous...') #2 /home/whitehouse/public_html/wp-load.php(37): require_once('/home/whitehous...') #3 /home/whitehouse/public_html/wp-blog-header.php(13): require_once('/home/whitehous...') #4 /home/whitehouse/public_html/index.php(17): require('/home/whitehous...') #5 {main} thrown in /home/whitehouse/public_html/wp-content/advanced-cache.php on line 6`
```

**Comment by tlovett1** [comment]
Fixed in 1.7.4
