### ISSUE TITLE
Weird error with the latest version

### ISSUE THREAD

**Issue by stefanos82** [tlovett1/simple-cache#94]
I have been testing this plugin since yesterday and have noticed a weird behavior at random times.

Out of curiosity, I have checked my log files and noticed the following messages inside my `error.log`:
```
2019/02/17 12:57:12 [error] 1071#1071: *20 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function sc_get_cache_path() in /var/www/html/example/app/wp-content/plugins/simple-cache/inc/class-sc-advanced-cache.php:59
Stack trace:
#0 /var/www/html/example/app/wp-includes/class-wp-hook.php(288): SC_Advanced_Cache->purge_post_on_comment_status_change('2')
#1 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/example/app/wp-includes/comment.php(2162): do_action('wp_set_comment_...', '2', 'approve')
#4 /var/www/html/example/app/wp-admin/includes/ajax-actions.php(819): wp_set_comment_status(Object(WP_Comment), 'approve', true)
#5 /var/www/html/example/app/wp-includes/class-wp-hook.php(286): wp_ajax_dim_comment('')
#6 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#7 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->" while reading response header from upstream, client: 192.168.10.4, server: example.dev, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "example.dev", referrer: "http://example.dev/wp-admin/edit-comments.php"
2019/02/17 13:01:47 [error] 1069#1069: *88 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function sc_get_cache_path() in /var/www/html/example/app/wp-content/plugins/simple-cache/inc/class-sc-advanced-cache.php:59
Stack trace:
#0 /var/www/html/example/app/wp-includes/class-wp-hook.php(288): SC_Advanced_Cache->purge_post_on_comment_status_change('3')
#1 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/example/app/wp-includes/comment.php(2162): do_action('wp_set_comment_...', '3', 'approve')
#4 /var/www/html/example/app/wp-admin/includes/ajax-actions.php(819): wp_set_comment_status(Object(WP_Comment), 'approve', true)
#5 /var/www/html/example/app/wp-includes/class-wp-hook.php(286): wp_ajax_dim_comment('')
#6 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#7 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->" while reading response header from upstream, client: 192.168.10.4, server: example.dev, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "example.dev", referrer: "http://example.dev/wp-admin/edit-comments.php"
2019/02/17 17:23:42 [alert] 10531#10531: *7591 sendfile() reported that "/var/www/html/example/app/wp-content/cache/simple-cache/example.dev//2019/01/hello-world//index.html" was truncated at 0 while sending response to client, client: 192.168.10.4, server: example.dev, request: "GET /2019/01/hello-world/ HTTP/1.1", host: "example.dev"
2019/02/17 17:26:27 [error] 10531#10531: *16554 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function sc_get_cache_path() in /var/www/html/example/app/wp-content/plugins/simple-cache/inc/class-sc-advanced-cache.php:59
Stack trace:
#0 /var/www/html/example/app/wp-includes/class-wp-hook.php(288): SC_Advanced_Cache->purge_post_on_comment_status_change('5')
#1 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/example/app/wp-includes/comment.php(2162): do_action('wp_set_comment_...', '5', 'approve')
#4 /var/www/html/example/app/wp-admin/includes/ajax-actions.php(819): wp_set_comment_status(Object(WP_Comment), 'approve', true)
#5 /var/www/html/example/app/wp-includes/class-wp-hook.php(286): wp_ajax_dim_comment('')
#6 /var/www/html/example/app/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#7 /var/www/html/example/app/wp-includes/plugin.php(453): WP_Hook->" while reading response header from upstream, client: 192.168.10.4, server: example.dev, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "example.dev", referrer: "http://example.dev/wp-admin/edit-comments.php"
```
I have looked all over the plugin and couldn't find anywhere about `sc_get_cache_path()`'s implementation.

Am I missing something here @tlovett1? :thinking:

**Comment by stefanos82** [comment]
OK, the error messages take place when I comment on an article and go as an admin user to approve it and I get this error message.

@tlovett1 any advice please?

**Comment by stefanos82** [comment]
I have looked all over the plugin and couldn't find anywhere about `sc_get_cache_path()`'s implementation.

Am I missing something here? :thinking:

**Comment by leewillis77** [comment]
I just hit this as well with Version 1.7.1 when approving a comment.

**Comment by jaygooby** [comment]
Looks like the function definition for `sc_get_cache_path()` was omitted from a commit. This PR fixes it: 

https://github.com/tlovett1/simple-cache/pull/98/commits/50ec710c5dec62ab449692e88d0c546972d5d444
